apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: default
data:
  DB_HOST: "mypsqlserver-82270864.postgres.database.azure.com"
  DB_PORT: "5432"
  DB_USER: "ktds"
  DB_PASS: "Ktds!1234"
